spring:
  profiles: local,default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.auto: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3306/springboot1
    username: root
    password: digitalriver
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.auto: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect